config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  get 'welcome/index'

  resources :articles, only: %i[show]

  namespace :administrate do
    get '/' => 'dashboards#index'

    resources :articles do
      member do
        delete :destroy_cover_image
      end
    end
    resources :categories
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'welcome#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category

  has_one_attached :cover_image do |attachable| # this is use  image processing
    attachable.variant :medium, resize_to_limit: [850, 650]
    attachable.variant :thumb, resize_to_limit: [325, 205]
    attachable.variant :cover, resize_to_limit: [200, 200]
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :articles
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/administrate/articles_controller.rb
# frozen_string_literal: true

module Administrate
  class ArticlesController < AdministrateController
    before_action :set_article, only: %i[destroy_cover_image show edit update destroy]
    before_action :set_categories, only: %i[show edit new]

    def index
      @articles = Article.includes(:category).all
    end

    def show; end

    def new
      @article = Article.new
    end

    def edit; end

    def create
      @article = Article.new(article_params)

      respond_to do |format|
        if @article.save
          format.html { redirect_to [:administrate, @article], notice: 'Artigo criado com sucesso .' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to [:administrate, @article], notice: 'Artigo atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @article.destroy!

      respond_to do |format|
        format.html do
          redirect_to administrate_articles_path, status: :see_other, notice: 'Artigo excluído com sucesso.'
        end
        format.json { head :no_content }
      end
    end

    def destroy_cover_image
      @article.cover_image.purge
      respond_to do |format|
        format.turbo_stream { render(turbo_stream: turbo_stream.remove(@article)) }
      end
    end

    private

    def set_categories
      @categories = Category.all
    end

    def set_article
      @article = Article.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :cover_image, :category_id)
    end
  end
end

app/controllers/administrate/categories_controller.rb
# frozen_string_literal: true

module Administrate
  class CategoriesController < AdministrateController
    before_action :set_category, only: %i[show edit update destroy]

    def index
      @categories = Category.all
    end

    def show; end

    def new
      @category = Category.new
    end

    def edit; end

    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to [:administrate, @category], notice: 'Category criado com sucesso .' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to [:administrate, @category], notice: 'Categoria atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @category }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      respond_to do |format|
        format.html do
          if @category.articles.empty?
            @category.destroy!
            redirect_to administrate_categories_path, status: :see_other, notice: 'Categoria excluído com sucesso.'
          else
            redirect_to administrate_categories_path, status: :see_other,
                                                      alert: 'Não foi possível excluir a categoria, categoria tem artigos associados.'
          end
        end
        format.json { head :no_content }
      end
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/administrate/dashboards_controller.rb
# frozen_string_literal: true

module Administrate
  class DashboardsController < AdministrateController
    def index; end
  end
end

app/controllers/administrate_controller.rb
# frozen_string_literal: true

class AdministrateController < ApplicationController
  before_action :authenticate_admin!
  layout 'administrate'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def show
    @article = Article.friendly.find(params[:id])
    @other_articles = Article.all.sample(3)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @articles = Article.all.limit(6).order(updated_at: :desc).limit(6)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  def active_link?(active_link)
    'active' if controller_name == active_link
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
  def cover_image(article, size = :thumb)
    article.cover_image.attached? ? article.cover_image.variant(size) : 'posts/post1.jpg'
  end
end

app/views/administrate/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <tr>
    <td> <%= l(article.created_at, format: :short) %></td>
    <td> <%= article.category.name %> </td>
    <td> <%= article.title %> </td>
    <td>
      <div class="icons">
        <%= link_to edit_administrate_article_path(article), title: 'Editar' do %>
          <%= image_tag 'icons/gray/edit.svg' %>
        <% end %>
        <%= link_to [:administrate, article], title: 'Visualizar' do %>
          <%= image_tag 'icons/gray/eye.svg' %>
        <% end %>

        <%= button_to [:administrate, article],class: 'button-transparent',alt: 'close', title: 'Apagar',data: {turbo: false}, method: :delete do %>
          <%= image_tag 'icons/gray/close.svg' %>
        <% end %>
      </div>
    </td>
  </tr>
</div>

app/views/administrate/articles/_form.html.erb
<div class="row">
  <%= form_with(model: [:administrate, article], class: 'form', id: 'article-form') do |form| %>
    <div class="input-row">
      <div class="input-container">
        <%= form.label :title, class: 'label' %>
        <%= form.text_field :title, disabled:  params[:action] == 'show', placeholder:'Digite aqui o título do artigo', class:'input' %>
      </div>
    </div>

    <div class="input-row">
      <div class="input-container">
        <%= form.label :body, class:'label' %>
        <%= form.text_area :body, disabled: params[:action] == 'show', rows:"18", class:'textarea', placeholder:'Escreva aqui o conteúdo do post' %>
      </div>
		</div>


    <div class="input-row">
      <div class="input-container">
        <%= form.label :category_id, class: 'label' %>
        <%= form.select :category_id, options_from_collection_for_select(@categories, :id, :name, article.category_id ), {}, {class: 'select',  disabled:  params[:action] == 'show'} %>
      </div>
    </div>

    <div>
      <%= form.label :cover_image, class: 'label-input-file', style: "display: block" %>
      <%= form.file_field :cover_image  if  params[:action] != 'show' %>
      <div id=<%= dom_id(article) %>>
        <%= image_tag article.cover_image.variant(:cover) if article.cover_image.attached? %>
        <%= link_to 'Remover', destroy_cover_image_administrate_article_path(article), data: {"turbo-confirm": "tem certeza?", "turbo-method": :delete} if article.cover_image.attached? &&  params[:action] != 'show' %>
      </div>
    </div>
     <%= button_to 'Apagar artigo', [:administrate, @article],data: {turbo: false}, method: :delete, class: 'button small' if params[:action] == 'show' %>
  <% end %>
</div>

app/views/administrate/articles/edit.html.erb
<%= link_to 'Artigos', administrate_articles_path, class: 'admin-title' %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Edição de artigo</h2>
    <div class="buttons">
      <a href="#" class="button small", onclick="document.forms['article-form'].submit()">
        <%= image_tag 'icons/white/edit.svg', alt: 'save' %>
        Salvar artigo
      </a>
    </div>
  </div>
  <%= render "form", article: @article %>
</div>

app/views/administrate/articles/index.html.erb
<h1 class="admin-title">Artigos</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Listagem de artigos</h2>
    <div class="buttons">
      <%= link_to new_administrate_article_path, class: 'button small' do %>
        <%= image_tag 'icons/white/add.svg', alt: 'add' %>
        Adicionar novo artigo
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>Data</th>
          <th>Categoria</th>
          <th>Nome</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
          <%= render partial: 'article', collection: @articles  %>
      </tbody>
    </table>
  </div>
</div>

app/views/administrate/articles/new.html.erb
 <%= link_to 'Artigos', administrate_articles_path, class: 'admin-title' %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Cadastro de artigo</h2>
    <div class="buttons">
      <a href="#" class="button small", onclick="document.forms['article-form'].submit()">
        <%= image_tag 'icons/white/save.svg', alt: 'save' %>
        Salvar artigo
      </a>
    </div>
  </div>
  <%= render "form", article: @article %>
</div>

app/views/administrate/articles/show.html.erb
<%= link_to 'Artigos', administrate_articles_path, class: 'admin-title' %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Visualização de artigo</h2>
    <div class="buttons">
      <%= link_to edit_administrate_article_path(@article), class:'button small' do %>
        <%= image_tag 'icons/white/edit.svg', alt: 'save' %>
        Editar artigo
      <% end %>
    </div>
  </div>
  <%= render "form", article: @article %>
</div>

app/views/administrate/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <tr>
    <td> <%= l(category.created_at, format: :short) %></td>
    <td> <%= category.name %> </td>
    <td>
      <div class="icons">
        <%= link_to edit_administrate_category_path(category), title: 'Editar' do %>
          <%= image_tag 'icons/gray/edit.svg' %>
        <% end %>
        <%= link_to [:administrate, category], title: 'Visualizar' do %>
          <%= image_tag 'icons/gray/eye.svg' %>
        <% end %>

        <%= button_to [:administrate, category],class: 'button-transparent',alt: 'close', title: 'Apagar',data: {turbo: false}, method: :delete do %>
          <%= image_tag 'icons/gray/close.svg' %>
        <% end %>
      </div>
    </td>
  </tr>
</div>

app/views/administrate/categories/_form.html.erb
<div class="row">
  <%= form_with(model: [:administrate, category], class: 'form', id: 'category-form') do |form| %>
    <div class="input-row">
      <div class="input-container">
        <%= form.label :name, class: 'label' %>
        <%= form.text_field :name, disabled:  params[:action] == 'show', placeholder:'Digite aqui o nome da categoria', class:'input' %>
      </div>
    </div>
     <%= button_to 'Apagar categoria', [:administrate, @category],data: {turbo: false}, method: :delete, class: 'button small' if params[:action] == 'show' %>
  <% end %>
</div>

app/views/administrate/categories/edit.html.erb
<%= link_to 'Categorias', administrate_categories_path, class: 'admin-title' %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Edição da categoria</h2>
    <div class="buttons">
      <a href="#" class="button small", onclick="document.forms['category-form'].submit()">
        <%= image_tag 'icons/white/edit.svg', alt: 'save' %>
        Editar categoria
      </a>
    </div>
  </div>
  <%= render "form", category: @category %>
</div>

app/views/administrate/categories/index.html.erb
<h1 class="admin-title">Categorias</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Listagem de Categorias</h2>
    <div class="buttons">
      <%= link_to new_administrate_category_path, class: 'button small' do %>
        <%= image_tag 'icons/white/add.svg', alt: 'add' %>
        Adicionar nova Categoria
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>Data</th>
          <th>Nome</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'category', collection: @categories  %>
      </tbody>
    </table>
  </div>
</div>

app/views/administrate/categories/new.html.erb
 <%= link_to 'Categorias', administrate_categories_path, class: 'admin-title' %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Cadastro de categoria</h2>
    <div class="buttons">
      <a href="#" class="button small", onclick="document.forms['category-form'].submit()">
        <%= image_tag 'icons/white/save.svg', alt: 'save' %>
        Salvar categoria
      </a>
    </div>
  </div>
  <%= render "form", category: @category %>
</div>

app/views/administrate/categories/show.html.erb
<%= link_to 'Artigos', administrate_categories_path, class: 'admin-title' %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Visualização de categoria</h2>
    <div class="buttons">
      <%= link_to edit_administrate_category_path(@category), class:'button small' do %>
        <%= image_tag 'icons/white/edit.svg', alt: 'save' %>
        Editar categoria
      <% end %>
    </div>
  </div>
  <%= render "form", category: @category %>
</div>

app/views/administrate/dashboards/index.html.erb
<h1 class='admin-title'>Seja bem vindo!</h1>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<section class="section posts-detail-title-section">
		<div class="container">
			<h1 class="post-detail-title"><%=@article.title%></h1>
		</div>
	</section>

	<section class="section post-detail-default-section post-detail-image-section">
		<div class="container">
			<div class="primary-content">
				<div class="post-detail-image">
          <%= image_tag cover_image(@article, :medium), alt: @article.title %>
				</div>
			</div>
			<div class="secondary-content">
				<a href="#" class="post-detail-image-ad">
          <%= image_tag 'ad/image-ad.jpg'%>
				</a>
				<div class="share-post">
					<div class="share-post-title">Compartilhar post</div>
					<div class="socials">

           <%= link_to "https://www.facebook.com/sharer/sharer.php?u=#{article_url(@article)}" do %>
						 <%= image_tag "icons/red/facebook.svg" %>
           <% end %>

            <%= link_to "https://twitter.com/intent/tweet?text=#{@article.title}&url=#{article_url(@article)}" do %>
						  <%= image_tag "icons/red/twitter.svg" %>
            <% end %>

					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="section post-detail-default-section author-section">
		<div class="container">
			<div class="primary-content">
				<div class="author">
					<div class="image-container">
             <%= image_tag 'author/jackson.jpg'%>
					</div>
					<div class="text-container">
						<div class="label">Autor</div>
						<div class="description">Jackson Pires</div>
					</div>
				</div>
				<div class="category text-container">
					<div class="label">Categoria</div>
					<div class="description"><%= @article.category.name %></div>
				</div>
				<div class="comments text-container">
					<div class="label">Comentários</div>
					<div class="description">15</div>
				</div>
			</div>
		</div>
	</section>


	<section class="section post-detail-default-section post-content-section">
		<div class="container">
			<div class="primary-content">
				<div class="post-detail-content">
					<p><%=@article.body%></p>
				</div>
				<div class="post-detail-author-bio">
					<div class="image">
              <%= image_tag 'author/jackson2.jpg'%>
						<div class="text-mobile">
							<div class="label">sobre o autor</div>
							<div class="author-name">Jackson Pires</div>
						</div>
					</div>
					<div class="text">
						<div class="label">sobre o autor</div>
						<div class="author-name">Jackson Pires</div>
						<div class="author-description">
							Desenvolvedor desde 1999. Especialista em Engenharia de Software com Ênfase em Software Livre. Professor
							acadêmico de 2009 até 2016. Entusiasta Ruby on Rails desde 2007. Atualmente mantendo o site Vídeos de TI e
							dedicando-se ao EAD com cursos na área de desenvolvimento de software, tendo treinado mais de 20.000
							pessoas.
						</div>
						<div class="author-social">
							<a href="#"><%= image_tag 'icons/gray/facebook.svg'%></a>
							<a href="#"><%= image_tag 'icons/gray/instagram.svg'%></a>
							<a href="#"><%= image_tag 'icons/gray/twitter.svg'%></a>
							<a href="#"><%= image_tag 'icons/gray/linkedin.svg'%></a>
							<a href="#"><%= image_tag 'icons/gray/youtube.svg'%></a>
						</div>
					</div>
				</div>
				<div class="post-detail-comment">
					<div class="comment-title-container">
						<div class="comment-title">Comentários</div>
						<div class="comment-actions">
							<div class="label">ordenar por: </div>
							<select class="select clean small">
								<option value="1">Últimos comentários</option>
								<option value="2">Mais recentes</option>
							</select>
						</div>
					</div>
					<div class="comment-form-container">
						<textarea class="textarea darker full double-padding"
							placeholder="Insira seu comentário aqui..."></textarea>
						<button class="button small">Publicar</button>
					</div>
					<div class="post-detail-comments-list">
						<div class="post-detail-comment-item">
							<div class="author-row">
								<div>
									<div class="avatar">
                    <%= image_tag 'avatar/man-1.svg'%>
									</div>
									<div class="name">Marcio Junior</div>
								</div>
								<div>
									<div class="date">30min atrás</div>
								</div>
							</div>
							<div class="description-row">
								<p>Wanted to ask if you’re available for a portrait shoot next week to ask if you’re available for a
									portrait shoot next week to ask if you’re available for a portrait shoot next week</p>
							</div>
							<div class="actions-row">
								<a href="#" class="like">6</a>
								<a href="#" class="deslike">4</a>
								<a href="#" class="share"></a>
							</div>
						</div>
						<div class="post-detail-comment-item">
							<div class="author-row">
								<div>
									<div class="avatar">
                    <%= image_tag 'avatar/woman-1.svg'%>
									</div>
									<div class="name">Ana Cristina</div>
								</div>
								<div>
									<div class="date">1hr atrás</div>
								</div>
							</div>
							<div class="description-row">
								<p>Wanted to ask if you’re available for a portrait shoot next week to ask if you’re available for a
									portrait shoot next week to ask if you’re available for a portrait shoot next week</p>
							</div>
							<div class="actions-row">
								<a href="#" class="like active">6</a>
								<a href="#" class="deslike">4</a>
								<a href="#" class="share"></a>
							</div>
						</div>
						<div class="post-detail-comment-item">
							<div class="author-row">
								<div>
									<div class="avatar">
                    <%= image_tag 'avatar/man-2.svg'%>
									</div>
									<div class="name">Igor Henrique</div>
								</div>
								<div>
									<div class="date">2 dias atrás</div>
								</div>
							</div>
							<div class="description-row">
								<p>Wanted to ask if you’re available for a portrait shoot next week to ask if you’re available for a
									portrait shoot next week to ask if you’re available for a portrait shoot next week</p>
							</div>
							<div class="actions-row">
								<a href="#" class="like">6</a>
								<a href="#" class="deslike active">4</a>
								<a href="#" class="share"></a>
							</div>
						</div>
						<div class="post-detail-comment-item">
							<div class="author-row">
								<div>
									<div class="avatar">
                    <%= image_tag 'avatar/woman-2.svg'%>
									</div>
									<div class="name">Maria Lúcia</div>
								</div>
								<div>
									<div class="date">30/09/2022</div>
								</div>
							</div>
							<div class="description-row">
								<p>Wanted to ask if you’re available for a portrait shoot next week to ask if you’re available for a
									portrait shoot next week to ask if you’re available for a portrait shoot next week</p>
							</div>
							<div class="actions-row">
								<a href="#" class="like">6</a>
								<a href="#" class="deslike">4</a>
								<a href="#" class="share"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="secondary-content">
				<a href="#" class="post-content-ad">
          <%= image_tag 'ad/post-content-ad.jpg'%>
				</a>
				<div class="post-detail-other-posts">
					<div class="other-posts-title">Outras publicações</div>
          <% @other_articles.each do |other_article|  %>
            <a href="#" class="post-resume">
              <%=  image_tag cover_image(other_article, :thumb), alt: other_article.title , class: 'post-resume-image'%>
              <h4 class="post-resume-title"><%= other_article.title %></h4>
            </a>
          <% end %>
				</div>
				<a href="#" class="post-content-ad">
          <%= image_tag 'ad/post-content-footer-ad.jpg'%>
				</a>
			</div>
		</div>
		</div>
	</section>

app/views/layouts/shared/administrate/_side_menu.html.erb
<aside class="admin-nav" id="adminMenu">
  <div class="row row-menu-button">
    <%= link_to  destroy_admin_session_path,class: 'logout', data: { turbo_method: :delete } do %>
      <%= image_tag 'icons/white/exit.svg', alt: 'exit' %>
    <% end %>
    <a href="#" id="adminMenuButton">
      <%= image_tag 'icons/white/menu.svg', alt: 'menu' %>
    </a>
  </div>
  <div class="row center">
    <%= link_to administrate_path, class: 'logo' do %>
      <%= image_tag 'logo.svg', alt: 'logo' %>
    <% end %>
  </div>
  <div class="row center column">
    <h3 class="user-name"><%= current_admin.name %></h3>
    <h4 class="user-email"><%= current_admin.email %> </h4>
  </div>
  <div class="row">
    <nav class="menu">
      <%= link_to administrate_articles_path, class: active_link?('articles') do %>
        <div class="icon">
          <%= image_tag 'icons/white/posts.svg' %>
        </div>
        <label for="#">Artigos</label>
      <% end %>

      <%= link_to administrate_categories_path,class: active_link?('categories') do %>
        <div class="icon">
          <%= image_tag 'icons/white/categories.svg' %>
        </div>
        <label for="#">Categorias</label>
      <% end %>
    </nav>
  </div>
</aside>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/welcome/_article.html.erb
<%= link_to  article_path(article), class: 'item' do %>
  <%= image_tag cover_image(article), class: 'item-image', alt: 'article image'  %>
  <div class="item-row">
    <div class="item-category">Backend</div>
    <div class="item-comments">25</div>
  </div>
  <div class="item-row">
    <div class="item-title"><%= article.title %></div>
  </div>
  <div class="item-row">
    <div class="item-author">Jackson Pires</div>
    <div class="item-date"><%= article.created_at %></div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%= render 'main_banner' %>
<%= render 'articles' %>
<%= render 'categories' %>